server:
  port: 5670

spring:
  application:
    name: fsdr-report
  datasource:
    url: jdbc:postgresql://localhost/postgres?currentSchema=report
    driver-class-name: org.postgresql.Driver
    schema: classpath:/schema.sql
    continue-on-error: false
    username: postgres
    password: postgres
    initialization-mode: always
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 10
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    uk.gov.ons.fsdr.report: DEBUG
    org.springframework.amqp: WARN
    org.hibernate: WARN
    org.springframework.amqp.rabbit.listener.ConditionalRejectingErrorHandler: ERROR

