server:
  port: 5670

spring:
  application:
    name: fsdr-report-writer
  datasource:
    url: jdbc:postgresql://localhost/postgres?currentSchema=report
    driver-class-name: org.postgresql.Driver
    schema: classpath:/schema.sql
    continue-on-error: false
    username: postgres
    password: postgres
    initialization-mode: always
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
logging:
  level:
    org.springframework.amqp: WARN
    org.hibernate: WARN

