create schema if not exists report;

create table if not exists report.report
(
    unique_employee_id                varchar(255) not null
        constraint report_pkey
            primary key,
    start_time                        varchar,
    job_title                         varchar,
    ingest_time                       varchar,
    adecco_create_employee_start      varchar,
    adecco_create_employee_complete   varchar,
    adecco_ingest_start               varchar,
    adecco_ingest_complete            varchar,
    nisra_create_start                varchar,
    nisra_create_complete             varchar,
    nisra_ingest_csv_start            varchar,
    nisra_ingest_csv_complete         varchar,
    nisra_extract_start               varchar,
    nisra_extract_complete            varchar,
    actions_start                     varchar,
    actions_complete                  varchar,
    action_type                       varchar,
    gsuite_action_start               varchar,
    gsuite_action_complete            varchar,
    gsuite_create_start               varchar,
    gsuite_create_complete            varchar,
    gsuite_area_group_start           varchar,
    gsuite_area_group_complete        varchar,
    gsuite_coordinator_group_start    varchar,
    gsuite_coordinator_group_complete varchar,
    gsuite_all_user_group_start       varchar,
    gsuite_all_user_group_complete    varchar,
    gsuite_survey_type_group_start    varchar,
    gsuite_survey_type_group_complete varchar,
    gsuite_team_drive_start           varchar,
    gsuite_team_drive_complete        varchar,
    xma_start                         varchar,
    xma_complete                      varchar,
    xma_devices_start                 varchar,
    xma_devices_complete              varchar,
    granby_start                      varchar,
    granby_complete                   varchar,
    snow_start                        varchar,
    snow_complete                     varchar,
    rca_start                         varchar,
    rca_complete                      varchar,
    lws_start                         varchar,
    lws_complete                      varchar
);